'pr::dependencies':
  - changed-files:
      - any-glob-to-any-file: ['package-lock.json', 'package.json']

'pr::docs':
  - changed-files:
      - any-glob-to-any-file: '**.md'

'pr::code':
  - changed-files:
      - any-glob-to-any-file: ['src/**/*.js']

'pr::types':
  - changed-files:
      - any-glob-to-any-file: ['src/index.d.js']

'pr::changeset':
  - changed-files:
      - any-glob-to-any-file: ['.changeset/**']

'pr::config':
  - changed-files:
      - any-glob-to-any-file:
          [
            'jsconfig.json',
            'eslint.config.js',
            '.prettierrc.json',
            '.prettierignore',
            'vite-end.d.ts',
            '.npmrc',
            '.gitignore',
          ]

'pr::vite':
  - changed-files:
      - any-glob-to-any-file: ['vite-end.d.ts', 'vite.config.js']

'pr::tests':
  - changed-files:
      - any-glob-to-any-file:
          [
            'tests/**.js',
            'tests/**.ts',
            '**/*.test.js',
            '**/*.test.ts',
            'src/testing/**',
          ]

'pr::github':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'pr::infra':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'pr::feature':
  - head-branch: ['feature', 'feat', 'enhancement', 'add']

'pr::patch':
  - head-branch: ['update', 'edit']

'pr::fix':
  - head-branch: ['fix', 'bug']
